{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 417,
   "metadata": {},
   "outputs": [],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "import requests\n",
    "import datetime #as dt\n",
    "from datetime import date \n",
    "from datetime import datetime\n",
    "import pandas as pd \n",
    "import re \n",
    "import numpy as np\n",
    "import sys\n",
    "import warnings\n",
    "from datetime import timedelta\n",
    "if not sys.warnoptions:\n",
    "    warnings.simplefilter(\"ignore\")\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC \n",
    "import time \n",
    "from selenium.webdriver.support.ui import Select\n",
    "from selenium.webdriver.common.action_chains import ActionChains\n",
    "from sympy.solvers import solve\n",
    "from sympy import Symbol\n",
    "import mysql.connector\n",
    "import sqlalchemy\n",
    "from mysql.connector import Error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 419,
   "metadata": {},
   "outputs": [],
   "source": [
    "start_time = time.time()\n",
    "\n",
    "def load_exists(driver):\n",
    "    try:\n",
    "        WebDriverWait(driver,10).until(EC.presence_of_element_located((By.CSS_SELECTOR, \"button.Button.SportsBoxAll.LoadMore\")))\n",
    "        return True\n",
    "    except:\n",
    "        return False\n",
    "\n",
    "def cookies(driver):\n",
    "    try:\n",
    "        driver.find_element_by_xpath('//*[@id=\"app\"]/div/span[2]/div/button')\n",
    "        return True\n",
    "    except:\n",
    "        return False       \n",
    "        \n",
    "def click_through(x):\n",
    "    if load_exists(x):\n",
    "        if cookies(x):\n",
    "            pisso= x.find_element_by_xpath('//*[@id=\"app\"]/div/span[2]/div/button')\n",
    "            ActionChains(x).move_to_element(pisso).click().perform()\n",
    "            element= x.find_element_by_css_selector(\"button.Button.SportsBoxAll.LoadMore\")\n",
    "            ActionChains(x).move_to_element(element).click().perform()\n",
    "            click_through(x)\n",
    "        else:\n",
    "            element= x.find_element_by_css_selector(\"button.Button.SportsBoxAll.LoadMore\")\n",
    "            ActionChains(x).move_to_element(element).click().perform()\n",
    "            click_through(x)\n",
    "    return x\n",
    "\n",
    "def get_links(browse):\n",
    "    rows= []\n",
    "    for thing in BeautifulSoup(browse.page_source,'lxml').find_all('li'):\n",
    "        if thing.find('a',{'class':'MatchTitleLink'}) and \\\n",
    "        pd.to_datetime(datetime.now()) <= pd.to_datetime(thing.find('span', {'class':'DateTime'}).text): \n",
    "            dict1= {}\n",
    "            match_link= 'https://www.betbrain.de' + thing.find('a', {'class':'MatchTitleLink'})['href']\n",
    "            date= pd.to_datetime(thing.find('span', {'class':'DateTime'}).text)\n",
    "            dict1.update({'match_link':match_link,'date':date})\n",
    "            rows.append(dict1)\n",
    "    df= pd.DataFrame(rows)\n",
    "    df=df[df['match_link'].str.contains(\"home-draw-away\")& df['match_link'].str.contains(\"football\")].reset_index(drop= True)\n",
    "    return df\n",
    "\n",
    "chrome_path= r'C:\\Users\\Iris\\Documents\\Nico\\NicoUni\\Practicum\\Python\\Projects\\WebDrivers\\chromedriver.exe'\n",
    "chrome_options = Options()\n",
    "chrome_options.add_argument('--headless')\n",
    "browser = webdriver.Chrome(\n",
    "executable_path=chrome_path, options=chrome_options)\n",
    "browser.get('https://www.betbrain.de/next-matches/')\n",
    "\n",
    "doc= click_through(browser)\n",
    "\n",
    "links= get_links(doc)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def xpath_exists(text,driver):\n",
    "    try:\n",
    "        WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,text)))\n",
    "        return True\n",
    "    except:\n",
    "        return False\n",
    "\n",
    "def get_odds(URL,playtime):\n",
    "    chrome_path= r'C:\\Users\\Iris\\Documents\\Nico\\NicoUni\\Practicum\\Python\\Projects\\WebDrivers\\chromedriver.exe'\n",
    "    chrome_options = Options()\n",
    "    chrome_options.add_argument('--headless')\n",
    "    browser = webdriver.Chrome(executable_path=chrome_path, options=chrome_options)\n",
    "    browser.get(URL)\n",
    "    if xpath_exists(\"//*[contains(text(), 'Pinnacle Sports')]\",browser):\n",
    "        if xpath_exists('//*[@id=\"app\"]/div/span/div/button',browser):\n",
    "            element= browser.find_element_by_xpath('//*[@id=\"app\"]/div/span/div/button')\n",
    "            ActionChains(browser).move_to_element(element).click().perform()\n",
    "        \n",
    "        country= browser.find_element_by_xpath('/html/body/div[1]/div/section/div/div/div/div[2]/div/div[1]/ul/li[4]/a/span[1]').text\n",
    "        league= browser.find_element_by_xpath('/html/body/div[1]/div/section/div/div/div/div[2]/div/div[1]/ul/li[5]/a/span[1]').text\n",
    "        html_page= browser.page_source\n",
    "        browser.quit()\n",
    "        soup= BeautifulSoup(html_page)\n",
    "        date= playtime + timedelta(hours= 2)\n",
    "        home_team= soup.find('p',{'class':'ScoresHome'}).findAll('span')[1].text\n",
    "        away_team= soup.find('p',{'class':'ScoresAway'}).findAll('span')[1].text\n",
    "        scrape_time= pd.to_datetime(datetime.now())\n",
    "        bookie_list= []\n",
    "        for thing in soup.findAll('div', {'class':'OTBookmakers'}):#\n",
    "            for element in thing.findAll('span', {'class':'BookieLogo BL'}):\n",
    "                bookie_list.append(element.find('span').text)\n",
    "        outcome= ['H','D','A']   \n",
    "        exclude= ['Betfair Exchange','Betfair']\n",
    "        \n",
    "        if any(x in exclude for x in bookie_list):\n",
    "            exchange= True\n",
    "        else:\n",
    "            exchange= False\n",
    "            \n",
    "        bookie_cols= [x.replace(' ','')+y for x in bookie_list for y in outcome if x not in exclude]\n",
    "        odds= []\n",
    "        for element in soup.findAll('a',{'class':['OTOddsLink', 'HasDeeplink']}):\n",
    "            odds.append(element.next_element.text[:-2])\n",
    "        keys= ['home_team','away_team','date','scrape_time','country','league']+bookie_cols\n",
    "        \n",
    "        if exchange:\n",
    "            values= [home_team, away_team, date,scrape_time,country,league]+odds[:-12]\n",
    "        else:\n",
    "            values= [home_team, away_team, date,scrape_time,country,league]+odds\n",
    "            \n",
    "        zipper= zip(keys, values)\n",
    "        match_dict= dict(zipper)\n",
    "    else:\n",
    "        match_dict= {}\n",
    "    \n",
    "    #time.sleep(0.5)\n",
    "    return match_dict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 421,
   "metadata": {},
   "outputs": [],
   "source": [
    "matches= []\n",
    "\n",
    "def append_matches(URLS):\n",
    "    global matches\n",
    "    for i in range(0,len(URLS)):\n",
    "        try:\n",
    "            matches.append(get_odds(URLS['match_link'][i], URLS['date'][i]))\n",
    "        except:\n",
    "            continue\n",
    "            \n",
    "#print (time.time() - start_time, \"seconds\")\n",
    "append_matches(links.loc[0:5].reset_index(drop=True))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 455,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>match_link</th>\n",
       "      <th>date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>https://www.betbrain.de/football/china/league-...</td>\n",
       "      <td>2021-05-24 08:00:00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                          match_link                date\n",
       "0  https://www.betbrain.de/football/china/league-... 2021-05-24 08:00:00"
      ]
     },
     "execution_count": 455,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "now= pd.to_datetime(datetime.now()+timedelta(hours= 6.5))\n",
    "links= links.query(\"date <=@now\").reset_index(drop= True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 422,
   "metadata": {},
   "outputs": [],
   "source": [
    "data= pd.DataFrame(matches)\n",
    "\n",
    "data['time_lag']= np.round((data['date']-data['scrape_time']).dt.total_seconds()/60,2)\n",
    "\n",
    "time_lag= data.pop('time_lag')\n",
    "data.insert(4, 'time_lag', time_lag)\n",
    "\n",
    "bookies= data.iloc[:,7:].columns\n",
    "homes= [x for x in bookies if x.endswith('H')]\n",
    "draws= [x for x in bookies if x.endswith('D')]\n",
    "aways= [x for x in bookies if x.endswith('A')]\n",
    "\n",
    "data[homes]= data[homes].astype('float16')\n",
    "data[draws]= data[draws].astype('float16')\n",
    "data[aways]= data[aways].astype('float16')\n",
    "\n",
    "\n",
    "data['maxOddsH']= data[homes].max(axis=1)\n",
    "data['maxOddsD']= data[draws].max(axis=1)\n",
    "data['maxOddsA']= data[aways].max(axis=1)\n",
    "\n",
    "data['maxBookieH']= data[homes].idxmax(axis=1)\n",
    "data['maxBookieD']= data[draws].idxmax(axis=1)\n",
    "data['maxBookieA']= data[aways].idxmax(axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 424,
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "def add_margins(probability, max_odds):\n",
    "    x= probability*(max_odds-1)-(1-probability)\n",
    "    return(x)\n",
    "\n",
    "#This is for Pinnacle \n",
    "\n",
    "cols= list(data.iloc[:,:7].columns)+['PinnacleSportsH','PinnacleSportsD','PinnacleSportsA','maxOddsH','maxOddsD','maxOddsA','maxBookieH', 'maxBookieD','maxBookieA']\n",
    "# equal margins \n",
    "try:\n",
    "    pinnacle= data[cols]\n",
    "    \n",
    "    test1= pinnacle.dropna(subset= ['PinnacleSportsH'])\n",
    "    test1['overround']= (1/test1['PinnacleSportsH']+1/test1['PinnacleSportsD']+1/test1['PinnacleSportsA'])-1\n",
    "    test1['ProbsPinnacleH-1']= 1/test1['PinnacleSportsH']/(1+test1['overround'])\n",
    "    test1['ProbsPinnacleD-1']= 1/test1['PinnacleSportsD']/(1+test1['overround'])\n",
    "    test1['ProbsPinnacleA-1']= 1/test1['PinnacleSportsA']/(1+test1['overround'])\n",
    "\n",
    "    test1['marginH-1']= test1['ProbsPinnacleH-1']*(test1['maxOddsH']-1)-(1-test1['ProbsPinnacleH-1'])\n",
    "    test1['marginD-1']= test1['ProbsPinnacleD-1']*(test1['maxOddsD']-1)-(1-test1['ProbsPinnacleD-1'])\n",
    "    test1['marginA-1']= test1['ProbsPinnacleA-1']*(test1['maxOddsA']-1)-(1-test1['ProbsPinnacleA-1'])\n",
    "\n",
    "#margins proportional to odds \n",
    "\n",
    "    test2= pinnacle.dropna(subset= ['PinnacleSportsH']) \n",
    "    test2['overround']= (1/test1['PinnacleSportsH']+1/test1['PinnacleSportsD']+1/test1['PinnacleSportsA'])-1\n",
    "    test2['ProbsPinnacleH-2']= 1/((3*test2['PinnacleSportsH'])/(3-(test2['overround']*test2['PinnacleSportsH'])))\n",
    "    test2['ProbsPinnacleD-2']= 1/((3*test2['PinnacleSportsD'])/(3-(test2['overround']*test2['PinnacleSportsD'])))\n",
    "    test2['ProbsPinnacleA-2']= 1/((3*test2['PinnacleSportsA'])/(3-(test2['overround']*test2['PinnacleSportsA'])))\n",
    "    \n",
    "    test2['marginH-2']= test2['ProbsPinnacleH-2']*(test2['maxOddsH']-1)-(1-test2['ProbsPinnacleH-2'])\n",
    "    test2['marginD-2']= test2['ProbsPinnacleD-2']*(test2['maxOddsD']-1)-(1-test2['ProbsPinnacleD-2'])\n",
    "    test2['marginA-2']= test2['ProbsPinnacleA-2']*(test2['maxOddsA']-1)-(1-test2['ProbsPinnacleA-2'])\n",
    "    \n",
    "    #test3= \n",
    "except:\n",
    "    test1= pd.DataFrame()\n",
    "    test2= pd.DataFrame\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Consensus group "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 442,
   "metadata": {},
   "outputs": [],
   "source": [
    "probs_homes= ['Probs'+x for x in bookies if x.endswith('H')]\n",
    "probs_draws= ['Probs'+x for x in bookies if x.endswith('D')]\n",
    "probs_aways= ['Probs'+x for x in bookies if x.endswith('A')]\n",
    "\n",
    "cons_test1= data \n",
    "# equal margins\n",
    "\n",
    "for odds in range(0, len(bookies),3):\n",
    "    overround= 1/cons_test1[bookies[odds]]+1/cons_test1[bookies[odds+1]]+1/cons_test1[bookies[odds+2]]\n",
    "    cons_test1['Probs'+bookies[odds]]= (1/cons_test1[bookies[odds]]/overround)\n",
    "    cons_test1['Probs'+bookies[odds+1]]= (1/cons_test1[bookies[odds+1]]/overround)\n",
    "    cons_test1['Probs'+bookies[odds+2]]= (1/cons_test1[bookies[odds+2]]/overround)\n",
    "    \n",
    "cons_test1['consProbsH-3']= cons_test1[probs_homes].mean(axis= 1)\n",
    "cons_test1['consProbsD-3']= cons_test1[probs_draws].mean(axis= 1)\n",
    "cons_test1['consProbsA-3']= cons_test1[probs_aways].mean(axis= 1)\n",
    "       \n",
    "cons_test1['marginH-3']= add_margins(cons_test1['consProbsH-3'],cons_test1['maxOddsH'])\n",
    "cons_test1['marginD-3']= add_margins(cons_test1['consProbsA-3'],cons_test1['maxOddsD'])\n",
    "cons_test1['marginA-3']= add_margins(cons_test1['consProbsD-3'],cons_test1['maxOddsA'])\n",
    "\n",
    "#proportional margins \n",
    "\n",
    "cons_test2= data \n",
    "\n",
    "for odd in range(0, len(bookies),3):\n",
    "    overround= (1/cons_test2[bookies[odd]]+1/cons_test2[bookies[odd+1]]+1/cons_test2[bookies[odd+2]])-1   \n",
    "    cons_test2['Probs'+bookies[odd]]= 1/((3*cons_test2[bookies[odd]])/(3-(overround*cons_test2[bookies[odd]])))\n",
    "    cons_test2['Probs'+bookies[odd+1]]= 1/((3*cons_test2[bookies[odd+1]])/(3-overround*cons_test2[bookies[odd+1]]))\n",
    "    cons_test2['Probs'+bookies[odd+2]]= 1/((3*cons_test2[bookies[odd+2]])/(3-(overround*cons_test2[bookies[odd+2]])))\n",
    "        \n",
    "                                                         \n",
    "cons_test2['consProbsH-4']= cons_test2[probs_homes].mean(axis= 1)\n",
    "cons_test2['consProbsD-4']= cons_test2[probs_draws].mean(axis= 1)\n",
    "cons_test2['consProbsA-4']= cons_test2[probs_aways].mean(axis= 1)\n",
    "\n",
    "cons_test2['marginH-4']= add_margins(cons_test2['consProbsH-4'],cons_test2['maxOddsH'])\n",
    "cons_test2['marginD-4']= add_margins(cons_test2['consProbsD-4'],cons_test2['maxOddsD'])\n",
    "cons_test2['marginA-4']= add_margins(cons_test2['consProbsA-4'],cons_test2['maxOddsA']) \n",
    "\n",
    "test3= cons_test1[['home_team','away_team','date','scrape_time','time_lag','country','league','maxOddsH','maxOddsD','maxOddsA','maxBookieH','maxBookieD','maxBookieA','consProbsH-3','consProbsD-3','consProbsA-3',\n",
    "'marginH-3','marginD-3', 'marginA-3']]\n",
    "\n",
    "test4= cons_test2[['home_team','away_team','date','scrape_time','time_lag','country','league','maxOddsH','maxOddsD','maxOddsA','maxBookieH','maxBookieD','maxBookieA','consProbsH-4','consProbsD-4','consProbsA-4',\n",
    "'marginH-4','marginD-4', 'marginA-4']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#save to sql "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_server_connection(host_name, user_name, user_password):\n",
    "    connection = None\n",
    "    try:\n",
    "        connection = mysql.connector.connect(\n",
    "            host=host_name,\n",
    "            user=user_name,\n",
    "            passwd=user_password\n",
    "        )\n",
    "        print(\"MySQL Database connection successful\")\n",
    "    except Error as err:\n",
    "        print(f\"Error: '{err}'\")\n",
    "\n",
    "    return connection\n",
    "\n",
    "\n",
    "def create_database(connection, query):\n",
    "    cursor = connection.cursor()\n",
    "    try:\n",
    "        cursor.execute(query)\n",
    "        print(\"Database created successfully\")\n",
    "    except Error as err:\n",
    "        print(f\"Error: '{err}'\")\n",
    "        \n",
    "\n",
    "def create_db_connection(host_name, user_name, user_password, db_name):\n",
    "    connection = None\n",
    "    try:\n",
    "        connection = mysql.connector.connect(\n",
    "            host=host_name,\n",
    "            user=user_name,\n",
    "            passwd=user_password,\n",
    "            database=db_name\n",
    "        )\n",
    "        print(\"MySQL Database connection successful\")\n",
    "    except Error as err:\n",
    "        print(f\"Error: '{err}'\")\n",
    "\n",
    "    return connection\n",
    "\n",
    "def read_query(connection, query):\n",
    "    cursor = connection.cursor()\n",
    "    result = None\n",
    "    try:\n",
    "        cursor.execute(query)\n",
    "        result = cursor.fetchall()\n",
    "        return result\n",
    "    except Error as err:\n",
    "        print(f\"Error: '{err}'\")\n",
    "    \n",
    "\n",
    "def execute_query(connection, query):\n",
    "    cursor = connection.cursor()\n",
    "    try:\n",
    "        cursor.execute(query)\n",
    "        connection.commit()\n",
    "        print(\"Query successful\")\n",
    "    except Error as err:\n",
    "        print(f\"Error: '{err}'\")\n",
    "        \n",
    "def get_colnames(database,tablename):\n",
    "    connection = create_db_connection(\"localhost\", \"root\", '4kS8GdBm!', database)\n",
    "    cursor = connection.cursor()\n",
    "    result = None\n",
    "    try:\n",
    "        cursor.execute(\"\"\"SELECT * FROM {table}\"\"\".format(table= tablename))\n",
    "        result= [i[0] for i in cursor.description]\n",
    "        return result\n",
    "    except Error as err:\n",
    "        print(f\"Error: '{err}'\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 410,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MySQL Database connection successful\n",
      "MySQL Database connection successful\n",
      "MySQL Database connection successful\n",
      "MySQL Database connection successful\n",
      "MySQL Database connection successful\n",
      "MySQL Database connection successful\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>home_team</th>\n",
       "      <th>away_team</th>\n",
       "      <th>date</th>\n",
       "      <th>scrape_time</th>\n",
       "      <th>time_lag</th>\n",
       "      <th>country</th>\n",
       "      <th>league</th>\n",
       "      <th>PinnacleSportsH</th>\n",
       "      <th>PinnacleSportsD</th>\n",
       "      <th>PinnacleSportsA</th>\n",
       "      <th>...</th>\n",
       "      <th>maxBookieH</th>\n",
       "      <th>maxBookieD</th>\n",
       "      <th>maxBookieA</th>\n",
       "      <th>overround</th>\n",
       "      <th>ProbsPinnacleH-1</th>\n",
       "      <th>ProbsPinnacleD-1</th>\n",
       "      <th>ProbsPinnacleA-1</th>\n",
       "      <th>marginH-1</th>\n",
       "      <th>marginD-1</th>\n",
       "      <th>marginA-1</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Hereford United</td>\n",
       "      <td>AFC Hornchurch</td>\n",
       "      <td>2021-05-22 17:15:00</td>\n",
       "      <td>2021-05-22 15:09:39</td>\n",
       "      <td>125.36</td>\n",
       "      <td>England</td>\n",
       "      <td>FA Trophy 2020/2021</td>\n",
       "      <td>1.839844</td>\n",
       "      <td>3.519531</td>\n",
       "      <td>4.218750</td>\n",
       "      <td>...</td>\n",
       "      <td>22BetH</td>\n",
       "      <td>22BetD</td>\n",
       "      <td>TotoGamingA</td>\n",
       "      <td>0.064453</td>\n",
       "      <td>0.510742</td>\n",
       "      <td>0.267090</td>\n",
       "      <td>0.222656</td>\n",
       "      <td>-0.055420</td>\n",
       "      <td>0.036621</td>\n",
       "      <td>-0.056152</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>NK Rudes Zagreb</td>\n",
       "      <td>NK Junak</td>\n",
       "      <td>2021-05-22 17:30:00</td>\n",
       "      <td>2021-05-22 15:09:57</td>\n",
       "      <td>140.06</td>\n",
       "      <td>Kroatien</td>\n",
       "      <td>2. HNL 2020/2021</td>\n",
       "      <td>1.309570</td>\n",
       "      <td>5.578125</td>\n",
       "      <td>8.179688</td>\n",
       "      <td>...</td>\n",
       "      <td>SportingbetH</td>\n",
       "      <td>PinnacleSportsD</td>\n",
       "      <td>bet-at-homeA</td>\n",
       "      <td>0.065430</td>\n",
       "      <td>0.716797</td>\n",
       "      <td>0.168335</td>\n",
       "      <td>0.114746</td>\n",
       "      <td>-0.017822</td>\n",
       "      <td>-0.061035</td>\n",
       "      <td>0.056152</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>NK Solin</td>\n",
       "      <td>NK Dugopolje</td>\n",
       "      <td>2021-05-22 17:30:00</td>\n",
       "      <td>2021-05-22 15:10:13</td>\n",
       "      <td>139.79</td>\n",
       "      <td>Kroatien</td>\n",
       "      <td>2. HNL 2020/2021</td>\n",
       "      <td>2.130859</td>\n",
       "      <td>3.560547</td>\n",
       "      <td>3.189453</td>\n",
       "      <td>...</td>\n",
       "      <td>SportingbetH</td>\n",
       "      <td>PinnacleSportsD</td>\n",
       "      <td>22BetA</td>\n",
       "      <td>0.063477</td>\n",
       "      <td>0.441162</td>\n",
       "      <td>0.263916</td>\n",
       "      <td>0.294678</td>\n",
       "      <td>-0.029785</td>\n",
       "      <td>-0.060547</td>\n",
       "      <td>-0.057129</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>NK Vihor</td>\n",
       "      <td>NK Slavonac Bukovlje</td>\n",
       "      <td>2021-05-22 17:30:00</td>\n",
       "      <td>2021-05-22 15:10:31</td>\n",
       "      <td>139.49</td>\n",
       "      <td>Kroatien</td>\n",
       "      <td>3. HNL 2021</td>\n",
       "      <td>1.549805</td>\n",
       "      <td>3.869141</td>\n",
       "      <td>4.718750</td>\n",
       "      <td>...</td>\n",
       "      <td>TotoGamingH</td>\n",
       "      <td>10BetD</td>\n",
       "      <td>10BetA</td>\n",
       "      <td>0.115234</td>\n",
       "      <td>0.578613</td>\n",
       "      <td>0.231812</td>\n",
       "      <td>0.190063</td>\n",
       "      <td>-0.045166</td>\n",
       "      <td>-0.061035</td>\n",
       "      <td>-0.059570</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Vukovar 1991</td>\n",
       "      <td>NK Kutjevo</td>\n",
       "      <td>2021-05-22 17:30:00</td>\n",
       "      <td>2021-05-22 15:10:46</td>\n",
       "      <td>139.23</td>\n",
       "      <td>Kroatien</td>\n",
       "      <td>3. HNL 2021</td>\n",
       "      <td>1.110352</td>\n",
       "      <td>7.460938</td>\n",
       "      <td>14.898438</td>\n",
       "      <td>...</td>\n",
       "      <td>Betano.deH</td>\n",
       "      <td>10BetD</td>\n",
       "      <td>WilliamHillA</td>\n",
       "      <td>0.101562</td>\n",
       "      <td>0.817383</td>\n",
       "      <td>0.121704</td>\n",
       "      <td>0.060944</td>\n",
       "      <td>-0.035767</td>\n",
       "      <td>-0.057129</td>\n",
       "      <td>0.036133</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 23 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         home_team             away_team                date  \\\n",
       "0  Hereford United        AFC Hornchurch 2021-05-22 17:15:00   \n",
       "1  NK Rudes Zagreb              NK Junak 2021-05-22 17:30:00   \n",
       "2         NK Solin          NK Dugopolje 2021-05-22 17:30:00   \n",
       "3         NK Vihor  NK Slavonac Bukovlje 2021-05-22 17:30:00   \n",
       "4     Vukovar 1991            NK Kutjevo 2021-05-22 17:30:00   \n",
       "\n",
       "          scrape_time  time_lag   country               league  \\\n",
       "0 2021-05-22 15:09:39    125.36   England  FA Trophy 2020/2021   \n",
       "1 2021-05-22 15:09:57    140.06  Kroatien     2. HNL 2020/2021   \n",
       "2 2021-05-22 15:10:13    139.79  Kroatien     2. HNL 2020/2021   \n",
       "3 2021-05-22 15:10:31    139.49  Kroatien          3. HNL 2021   \n",
       "4 2021-05-22 15:10:46    139.23  Kroatien          3. HNL 2021   \n",
       "\n",
       "   PinnacleSportsH  PinnacleSportsD  PinnacleSportsA  ...    maxBookieH  \\\n",
       "0         1.839844         3.519531         4.218750  ...        22BetH   \n",
       "1         1.309570         5.578125         8.179688  ...  SportingbetH   \n",
       "2         2.130859         3.560547         3.189453  ...  SportingbetH   \n",
       "3         1.549805         3.869141         4.718750  ...   TotoGamingH   \n",
       "4         1.110352         7.460938        14.898438  ...    Betano.deH   \n",
       "\n",
       "        maxBookieD    maxBookieA overround ProbsPinnacleH-1 ProbsPinnacleD-1  \\\n",
       "0           22BetD   TotoGamingA  0.064453         0.510742         0.267090   \n",
       "1  PinnacleSportsD  bet-at-homeA  0.065430         0.716797         0.168335   \n",
       "2  PinnacleSportsD        22BetA  0.063477         0.441162         0.263916   \n",
       "3           10BetD        10BetA  0.115234         0.578613         0.231812   \n",
       "4           10BetD  WilliamHillA  0.101562         0.817383         0.121704   \n",
       "\n",
       "   ProbsPinnacleA-1  marginH-1  marginD-1  marginA-1  \n",
       "0          0.222656  -0.055420   0.036621  -0.056152  \n",
       "1          0.114746  -0.017822  -0.061035   0.056152  \n",
       "2          0.294678  -0.029785  -0.060547  -0.057129  \n",
       "3          0.190063  -0.045166  -0.061035  -0.059570  \n",
       "4          0.060944  -0.035767  -0.057129   0.036133  \n",
       "\n",
       "[5 rows x 23 columns]"
      ]
     },
     "execution_count": 410,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#connection= create_server_connection(db_ip,\"root\",\"4kS8GdBm!\")\n",
    "connection= create_db_connection(db_ip, \"root\", \"4kS8GdBm!\",\"betting_football\")\n",
    "\n",
    "oldfix= pd.DataFrame(read_query(connection,\"SELECT * FROM fixtures\"),columns= get_colnames('betting_football','fixtures'))\n",
    "old1= pd.DataFrame(read_query(connection,\"SELECT * FROM test_group1\"),columns= get_colnames('betting_football','test_group1'))\n",
    "old2= pd.DataFrame(read_query(connection,\"SELECT * FROM test_group2\"),columns= get_colnames('betting_football','test_group2'))\n",
    "old3= pd.DataFrame(read_query(connection,\"SELECT * FROM test_group3\"),columns= get_colnames('betting_football','test_group3'))\n",
    "old4= pd.DataFrame(read_query(connection,\"SELECT * FROM test_group4\"),columns= get_colnames('betting_football','test_group4'))\n",
    "\n",
    "fixtures= fixtures.append(oldfix)\n",
    "test1= test1.append(old1)\n",
    "test2= test2.append(old2)\n",
    "test3= test3.append(old3)\n",
    "test4= test4.append(old4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 361,
   "metadata": {},
   "outputs": [],
   "source": [
    "db_username= \"root\"\n",
    "db_password= '4kS8GdBm!'\n",
    "db_ip= \"localhost\"\n",
    "db_name= 'betting_football'\n",
    "\n",
    "db_connection = sqlalchemy.create_engine('mysql+mysqlconnector://{0}:{1}@{2}/{3}'.\n",
    "                                               format(db_username, db_password, \n",
    "                                                      db_ip, db_name))\n",
    "\n",
    "data.to_sql('fixtures',db_connection,if_exists= 'replace', index= False)\n",
    "test1.to_sql('test_group1',db_connection,if_exists= 'append', index= False)\n",
    "test2.to_sql('test_group2',db_connection,if_exists= 'append', index= False)\n",
    "test3.to_sql('test_group3',db_connection,if_exists= 'append', index= False)\n",
    "test4.to_sql('test_group4',db_connection,if_exists= 'append', index= False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
